name: Setup Cloud Scheduler for Fear & Greed Clean Data Fetch

on:
  push:
    branches:
      - prod
    paths:
      - "src/fear_and_greed/processing/main.py"

jobs:
  setup-scheduler:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

       - name: Deploy Cloud Function fear-greed-clean
         run: |
          gcloud functions deploy fear-greed-clean \
            --region=europe-west1 \
            --runtime=python310 \
            --trigger-topic=trigger-clean-fear-greed \
            --entry-point=ingest_fear_greed_clean \
            --source=src/fear_and_greed/processing \
            --allow-unauthenticated