name: Setup Cloud Scheduler for OHLC Clean Data Fetch

on:
  push:
    branches:
      - prod
    paths:
      - "src/ohlc/processing/main.py"

jobs:
  setup-scheduler:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

     - name: Deploy Cloud Function ohlc-clean
        run: |
          gcloud functions deploy ohlc-clean \
            --region=europe-west1 \
            --runtime=python310 \
            --trigger-topic=trigger-clean-ohlc \
            --entry-point=ingest_ohlc_clean \
            --source=src/ohlc/processing \
            --allow-unauthenticated