name: Deploy Cloud Scheduler Jobs

on:
  push:
    branches:
      - main
    paths:
      - "cloud-scheduler/**" # Trigger workflow when any scheduler file changes

jobs:
  deploy-schedulers:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy Cloud Scheduler Jobs
        run: |
          for file in cloud-scheduler/*.yaml; do
            job_name=$(basename $file .yaml)
            schedule=$(yq eval '.schedule' $file)
            uri=$(yq eval '.http_target.uri' $file)
            time_zone=$(yq eval '.time_zone' $file)
            service_account=$(yq eval '.http_target.oauth_token.service_account_email' $file)

            gcloud scheduler jobs create http $job_name \
              --schedule="$schedule" \
              --time-zone="$time_zone" \
              --http-method=POST \
              --uri="$uri" \
              --oauth-service-account-email="$service_account" || \
            gcloud scheduler jobs update http $job_name \
              --schedule="$schedule" \
              --time-zone="$time_zone" \
              --http-method=POST \
              --uri="$uri" \
              --oauth-service-account-email="$service_account"
          done
