---
name: Static Analysis

on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.py"
  pull_request:
    branches:
      - main
    paths:
      - "src/**/*.py"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Run mypy for static type checking
        run: |
          mypy src/
