name: YAML Validation

on:
  push:
    branches:
      - main
    paths:
      - "**/*.yaml"
      - "**/*.yml"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.yaml"
      - "**/*.yml"

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install YAML lint
        run: |
          sudo apt-get update
          sudo apt-get install yamllint

      - name: Validate YAML files
        run: |
          yamllint .
